### PR TITLE
Switch to SubProcess for better control

### LINKED ISSUE #124: Running different apps in sequence doesn't work
Steps to Reproduce
* Run a session in one app
* Run a session in another app
* The second session will keep using the signed debug apk from the first session

The way I was able to work around it was wiping the data on the emulator

### PR DESCRIPTION
**Pull request by imurchie**
`SubProcess` allows us to have a handle on the running instrumentation process, while `exec` is meant to be fire-and-forget.

Finally fix #124 in Travis.

### CODE REVIEW

File: lib/espresso-runner.js [hunk 1]
```diff
@@ -47,10 +48,13 @@ class EspressoRunner {
     logger.info(`Repackaging espresso server for: '${this.appPackage}'`);
     let packageTmpDir = path.resolve(this.tmpDir, this.appPackage);
     let newManifestPath = path.resolve(this.tmpDir, 'AndroidManifest.xml');
+    if (await fs.exists(newManifestPath)) {
```
Comment (mykola-mokhnach) [inline lib/espresso-runner.js]: rimraf?

File: lib/espresso-runner.js [hunk 2]
```diff
@@ -101,6 +115,8 @@ class EspressoRunner {
       logger.warn(`Did not get confirmation Espresso deleteSession worked; ` +
           `Error was: ${err}`);
     }
+
+    await this.instProcess.stop();
```
Comment (mykola-mokhnach) [inline lib/espresso-runner.js]: should we check if the process is running?

File: lib/espresso-runner.js [hunk 3]
```diff
@@ -66,29 +70,39 @@ class EspressoRunner {
...
+      logger.debug(`[Instrumentation]${line.trim()}`);
+    });
+
+    await this.instProcess.start((stdout, stderr) => {
+      if (stdout.includes('io.appium.espressoserver.EspressoServerRunnerTest:')) {
+        return true;
+      }
+      if (stderr.includes('Exception')) {
+        throw new Error(stderr.trim());
+      }
```
Comment (mykola-mokhnach) [inline lib/espresso-runner.js]: What is going to happen if none of the conditions have been reached?

File: lib/espresso-runner.js [hunk 4]
```diff
@@ -66,29 +70,39 @@ class EspressoRunner {
   }
 
   async startSession (caps) {
-    let cmd = ['am', 'instrument', '-w', '-e', 'debug', process.env.ESPRESSO_JAVA_DEBUG === 'true' ? 'true' : 'false',
+    let cmd = ['shell', 'am', 'instrument', '-w', '-e', 'debug', process.env.ESPRESSO_JAVA_DEBUG === 'true' ? 'true' : 'false',
```
Comment (mykola-mokhnach) [inline lib/espresso-runner.js]: It might be more readable to group some options, for example:
```
const cmd = [
  'shell'
  'am', 'instrument', 
  '-w',
   '-e', process.env.ESPRESSO_JAVA_DEBUG === 'true' ? 'true' : 'false'
...
]
```

File: lib/espresso-runner.js (hunk 3 above)
Comment (jlipps) [reply lib/espresso-runner.js]: @mykola-mokhnach a timeout error will be thrown
